name = "giapha-api"
main = "cloudflare/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "giapha-db"
database_id = "f0e6540a-5d5b-466c-8f18-2a775887b389"

[triggers]
crons = ["0 0 * * *"]
